### ISSUE TITLE
Style Template Selection and Customization Page

### ISSUE THREAD

**Issue by AnamarisOrtiz** [amritank/bravissimo#23]
# Description:
Create and apply styles to the template selection and customization page, including the live preview section.

# Tasks:

-[ ] Design the layout for the template selection and customization page.
-[ ] Apply CSS styles to enhance visual appeal and usability.
-[ ] Ensure responsiveness for different screen sizes.
-[ ] Style the live preview section to reflect user selections.

Acceptance Criteria:
Template selection and customization page has a visually appealing and user-friendly design.
Page is responsive and works well on different devices.
Live preview section accurately reflects user selections in real-time.

**Comment by amritank** [comment]
I can take this up
